In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd()
while not (project_root / "src").exists():
    project_root = project_root.parent

sys.path.insert(0, str(project_root / "src"))

### Testing ReLU


In [3]:
from tinytorch.activations import ReLU_CP
from torch.nn import ReLU
from tinytorch.tensor import Tensor_CP
from torch import Tensor
import numpy as np

In [4]:
x = Tensor(np.random.randn(3, 4) * 5)
x.data

tensor([[-10.2531,  -2.2776,  -3.4928,  -3.9596],
        [ -0.2617,  -6.0550,  -8.4906,  -3.5657],
        [  3.1961,  -3.8373,  -2.8674,  -0.0279]])

In [5]:
relu = ReLU()
y = relu(x)

print("Input x:")
print(x.data)

print("\nAfter ReLU:")
print(y.data)

Input x:
tensor([[-10.2531,  -2.2776,  -3.4928,  -3.9596],
        [ -0.2617,  -6.0550,  -8.4906,  -3.5657],
        [  3.1961,  -3.8373,  -2.8674,  -0.0279]])

After ReLU:
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [3.1961, 0.0000, 0.0000, 0.0000]])


### Manual ReLU

In [6]:
x = Tensor_CP(np.random.randn(3, 4) * 5)
x.data

array([[-0.8185522 , -2.1401224 ,  7.765377  ,  0.04188354],
       [12.549994  ,  1.4608194 ,  7.9603286 , 13.604726  ],
       [ 5.275889  ,  0.97899485,  4.0053596 ,  9.816178  ]],
      dtype=float32)

In [7]:
relu = ReLU_CP()
y = relu(x)

print("Input x:")
print(x.data)

print("\nAfter ReLU:")
print(y.data)

Input x:
[[-0.8185522  -2.1401224   7.765377    0.04188354]
 [12.549994    1.4608194   7.9603286  13.604726  ]
 [ 5.275889    0.97899485  4.0053596   9.816178  ]]

After ReLU:
[[ 0.          0.          7.765377    0.04188354]
 [12.549994    1.4608194   7.9603286  13.604726  ]
 [ 5.275889    0.97899485  4.0053596   9.816178  ]]
